//TFTInsights
export const RETURN_TFT_INSIGHTS = 'RETURN_TFT_INSIGHTS';
export const FAIL_RETURN_TFT_INSIGHTS = 'FAIL_RETURN_TFT_INSIGHTS';
export const CHANGE_TFT_INSIGHTS_REGION = 'CHANGE_TFT_INSIGHTS_REGION';
export const START_TFT_INSIGHTS_REQUEST = 'START_TFT_INSIGHTS_REQUEST';

//TFTProfile
export const RETURN_TFT_PROFILE = 'RETURN_TFT_PROFILE';
export const FAIL_RETURN_TFT_PROFILE = 'FAIL_RETURN_TFT_PROFILE';
export const START_TFT_PROFILE_REQUEST = 'START_TFT_PROFILE_REQUEST';

//RiftProfile
export const RETURN_RIFT_PROFILE = 'RETURN_RIFT_PROFILE';
export const FAIL_RETURN_RIFT_PROFILE = 'FAIL_RETURN_RIFT_PROFILE';
export const START_RIFT_PROFILE_REQUEST = 'START_RIFT_PROFILE_REQUEST';

//Search
export const RETURN_SUMMONERS = 'RETURN_SUMMONERS';
export const FAIL_RETURN_SUMMONERS= 'FAIL_RETURN_SUMMONERS';
export const CHANGE_SUMMONERS_REGION = 'CHANGE_TFT_INSIGHTS_REGION';
export const RESET_PROFILES = 'RESET_PROFILES';

//Nav
export const SET_TAB = 'SET_TAB';