//TFTInsights
export const RETURN_TFT_INSIGHTS = 'RETURN_TFT_INSIGHTS';
export const FAIL_RETURN_TFT_INSIGHTS = 'FAIL_RETURN_TFT_INSIGHTS';
export const CHANGE_TFT_INSIGHTS_REGION = 'CHANGE_TFT_INSIGHTS_REGION';
export const START_TFT_INSIGHTS_REQUEST = 'START_TFT_INSIGHTS_REQUEST';

//Search
export const RETURN_SUMMONERS = 'RETURN_SUMMONERS';
export const FAIL_RETURN_SUMMONERS= 'FAIL_RETURN_SUMMONERS';
export const CHANGE_SUMMONERS_REGION = 'CHANGE_TFT_INSIGHTS_REGION';